// ==========================================
// [데이터 전용 파일] src/hanjaData.js
// 한자 및 교과서 어휘 데이터를 이곳에서 통합 관리합니다.
// ==========================================

// ----------------------------------------------------------------------
// [PART 1] 기초 한자 데이터 (쓰기/매칭 게임용)
// ----------------------------------------------------------------------

// 8급 (30자) - 전수 검토 완료
export const HANJA_LEVEL_8 = [
  { id: 1, char: '九', sound: '아홉', meaning: '구' },
  { id: 2, char: '金', sound: '쇠', meaning: '금' },
  { id: 3, char: '南', sound: '남녘', meaning: '남' },
  { id: 4, char: '男', sound: '사내', meaning: '남' },
  { id: 5, char: '女', sound: '여자', meaning: '녀' },
  { id: 6, char: '東', sound: '동녘', meaning: '동' },
  { id: 7, char: '六', sound: '여섯', meaning: '륙' },
  { id: 8, char: '母', sound: '어머니', meaning: '모' },
  { id: 9, char: '木', sound: '나무', meaning: '목' },
  { id: 10, char: '門', sound: '문', meaning: '문' },
  { id: 11, char: '父', sound: '아버지', meaning: '부' },
  { id: 12, char: '北', sound: '북녘', meaning: '북' },
  { id: 13, char: '四', sound: '넉', meaning: '사' },
  { id: 14, char: '三', sound: '석', meaning: '삼' },
  { id: 15, char: '西', sound: '서녘', meaning: '서' },
  { id: 16, char: '水', sound: '물', meaning: '수' },
  { id: 17, char: '十', sound: '열', meaning: '십' },
  { id: 18, char: '五', sound: '다섯', meaning: '오' },
  { id: 19, char: '月', sound: '달', meaning: '월' },
  { id: 20, char: '二', sound: '두', meaning: '이' },
  { id: 21, char: '人', sound: '사람', meaning: '인' },
  { id: 22, char: '日', sound: '날', meaning: '일' },
  { id: 23, char: '一', sound: '한', meaning: '일' },
  { id: 24, char: '子', sound: '아들', meaning: '자' },
  { id: 25, char: '弟', sound: '아우', meaning: '제' },
  { id: 26, char: '七', sound: '일곱', meaning: '칠' },
  { id: 27, char: '土', sound: '흙', meaning: '토' },
  { id: 28, char: '八', sound: '여덟', meaning: '팔' },
  { id: 29, char: '兄', sound: '맏', meaning: '형' },
  { id: 30, char: '火', sound: '불', meaning: '화' }
];

// 7급 (20자)
export const HANJA_LEVEL_7 = [
  { id: 31, char: '江', sound: '강', meaning: '강' },
  { id: 32, char: '口', sound: '입', meaning: '구' },
  { id: 33, char: '內', sound: '안', meaning: '내' },
  { id: 34, char: '年', sound: '해', meaning: '년' },
  { id: 35, char: '大', sound: '큰', meaning: '대' },
  { id: 36, char: '目', sound: '눈', meaning: '목' },
  { id: 37, char: '白', sound: '흰', meaning: '백' },
  { id: 38, char: '山', sound: '메(뫼)', meaning: '산' },
  { id: 39, char: '上', sound: '위', meaning: '상' },
  { id: 40, char: '小', sound: '작을', meaning: '소' },
  { id: 41, char: '手', sound: '손', meaning: '수' },
  { id: 42, char: '外', sound: '바깥', meaning: '외' },
  { id: 43, char: '右', sound: '오른', meaning: '우' },
  { id: 44, char: '入', sound: '들', meaning: '입' },
  { id: 45, char: '足', sound: '발', meaning: '족' },
  { id: 46, char: '左', sound: '왼', meaning: '좌' },
  { id: 47, char: '中', sound: '가운데', meaning: '중' },
  { id: 48, char: '靑', sound: '푸를', meaning: '청' },
  { id: 49, char: '出', sound: '날', meaning: '출' },
  { id: 50, char: '下', sound: '아래', meaning: '하' }
];

// 6급 (20자)
export const HANJA_LEVEL_6 = [
  { id: 51, char: '犬', sound: '개', meaning: '견' },
  { id: 52, char: '己', sound: '몸', meaning: '기' },
  { id: 53, char: '林', sound: '수풀', meaning: '림' },
  { id: 54, char: '馬', sound: '말', meaning: '마' },
  { id: 55, char: '名', sound: '이름', meaning: '명' },
  { id: 56, char: '百', sound: '일백', meaning: '백' },
  { id: 57, char: '生', sound: '날', meaning: '생' },
  { id: 58, char: '石', sound: '돌', meaning: '석' },
  { id: 59, char: '先', sound: '먼저', meaning: '선' },
  { id: 60, char: '姓', sound: '성씨', meaning: '성' },
  { id: 61, char: '心', sound: '마음', meaning: '심' },
  { id: 62, char: '羊', sound: '양', meaning: '양' },
  { id: 63, char: '魚', sound: '물고기', meaning: '어' },
  { id: 64, char: '玉', sound: '구슬', meaning: '옥' },
  { id: 65, char: '牛', sound: '소', meaning: '우' },
  { id: 66, char: '耳', sound: '귀', meaning: '이' },
  { id: 67, char: '地', sound: '땅', meaning: '지' },
  { id: 68, char: '川', sound: '내', meaning: '천' },
  { id: 69, char: '千', sound: '일천', meaning: '천' },
  { id: 70, char: '天', sound: '하늘', meaning: '천' }
];

// 준5급 (81자)
export const HANJA_LEVEL_5_JUN = [
  { id: 71, char: '車', sound: '수레', meaning: '거' },
  { id: 72, char: '巾', sound: '수건', meaning: '건' },
  { id: 73, char: '古', sound: '예', meaning: '고' },
  { id: 74, char: '工', sound: '장인', meaning: '공' },
  { id: 75, char: '今', sound: '이제', meaning: '금' },
  { id: 76, char: '同', sound: '한가지', meaning: '동' },
  { id: 77, char: '力', sound: '힘', meaning: '력' },
  { id: 78, char: '立', sound: '설', meaning: '립' },
  { id: 79, char: '末', sound: '끝', meaning: '말' },
  { id: 80, char: '文', sound: '글월', meaning: '문' },
  { id: 81, char: '方', sound: '모', meaning: '방' },
  { id: 82, char: '本', sound: '근본', meaning: '본' },
  { id: 83, char: '夫', sound: '지아비', meaning: '부' },
  { id: 84, char: '不', sound: '아니', meaning: '불' },
  { id: 85, char: '士', sound: '선비', meaning: '사' },
  { id: 86, char: '夕', sound: '저녁', meaning: '석' },
  { id: 87, char: '世', sound: '세상', meaning: '세' },
  { id: 88, char: '少', sound: '적을', meaning: '소' },
  { id: 89, char: '食', sound: '먹을', meaning: '식' },
  { id: 90, char: '央', sound: '가운데', meaning: '앙' },
  { id: 91, char: '王', sound: '임금', meaning: '왕' },
  { id: 92, char: '位', sound: '자리', meaning: '위' },
  { id: 93, char: '衣', sound: '옷', meaning: '의' },
  { id: 94, char: '字', sound: '글자', meaning: '자' },
  { id: 95, char: '自', sound: '스스로', meaning: '자' },
  { id: 96, char: '正', sound: '바를', meaning: '정' },
  { id: 97, char: '主', sound: '주인', meaning: '주' },
  { id: 98, char: '寸', sound: '마디', meaning: '촌' },
  { id: 99, char: '向', sound: '향할', meaning: '향' },
  { id: 100, char: '休', sound: '쉴', meaning: '휴' }
];

// 5급 (110자)
export const HANJA_LEVEL_5 = [
  { id: 101, char: '歌', sound: '노래', meaning: '가' },
  { id: 102, char: '家', sound: '집', meaning: '가' },
  { id: 103, char: '各', sound: '각각', meaning: '각' },
  { id: 104, char: '間', sound: '사이', meaning: '간' },
  { id: 105, char: '强', sound: '강할', meaning: '강' },
  { id: 106, char: '開', sound: '열', meaning: '개' },
  { id: 107, char: '去', sound: '갈', meaning: '거' },
  { id: 108, char: '見', sound: '볼', meaning: '견' },
  { id: 109, char: '京', sound: '서울', meaning: '경' },
  { id: 110, char: '計', sound: '셀', meaning: '계' },
  { id: 111, char: '高', sound: '높을', meaning: '고' },
  { id: 112, char: '功', sound: '공', meaning: '공' },
  { id: 113, char: '空', sound: '빌', meaning: '공' },
  { id: 114, char: '共', sound: '함께', meaning: '공' },
  { id: 115, char: '科', sound: '과목', meaning: '과' },
  { id: 116, char: '光', sound: '빛', meaning: '광' },
  { id: 117, char: '敎', sound: '가르칠', meaning: '교' },
  { id: 118, char: '交', sound: '사귈', meaning: '교' },
  { id: 119, char: '校', sound: '학교', meaning: '교' },
  { id: 120, char: '區', sound: '나눌', meaning: '구' },
  { id: 121, char: '國', sound: '나라', meaning: '국' },
  { id: 122, char: '軍', sound: '군사', meaning: '군' },
  { id: 123, char: '近', sound: '가까울', meaning: '근' },
  { id: 124, char: '急', sound: '급할', meaning: '급' },
  { id: 125, char: '旗', sound: '기', meaning: '기' },
  { id: 126, char: '記', sound: '기록할', meaning: '기' },
  { id: 127, char: '氣', sound: '기운', meaning: '기' },
  { id: 128, char: '農', sound: '농사', meaning: '농' },
  { id: 129, char: '多', sound: '많을', meaning: '다' },
  { id: 130, char: '短', sound: '짧을', meaning: '단' },
  { id: 131, char: '答', sound: '대답', meaning: '답' },
  { id: 132, char: '當', sound: '마땅할', meaning: '당' },
  { id: 133, char: '對', sound: '대답할', meaning: '대' },
  { id: 134, char: '代', sound: '대신할', meaning: '대' },
  { id: 135, char: '道', sound: '길', meaning: '도' },
  { id: 136, char: '刀', sound: '칼', meaning: '도' },
  { id: 137, char: '讀', sound: '읽을', meaning: '독' },
  { id: 138, char: '冬', sound: '겨울', meaning: '동' },
  { id: 139, char: '洞', sound: '고을', meaning: '동' },
  { id: 140, char: '頭', sound: '머리', meaning: '두' },
  { id: 141, char: '等', sound: '무리', meaning: '등' },
  { id: 142, char: '登', sound: '오를', meaning: '등' },
  { id: 143, char: '樂', sound: '즐거울', meaning: '락' },
  { id: 144, char: '來', sound: '올', meaning: '래' },
  { id: 145, char: '老', sound: '늙을', meaning: '로' },
  { id: 146, char: '理', sound: '다스릴', meaning: '리' },
  { id: 147, char: '里', sound: '마을', meaning: '리' },
  { id: 148, char: '利', sound: '이로울', meaning: '리' },
  { id: 149, char: '萬', sound: '일만', meaning: '만' },
  { id: 150, char: '每', sound: '매양', meaning: '매' },
  { id: 151, char: '面', sound: '낯', meaning: '면' },
  { id: 152, char: '命', sound: '목숨', meaning: '명' },
  { id: 153, char: '明', sound: '밝을', meaning: '명' },
  { id: 154, char: '毛', sound: '털', meaning: '모' },
  { id: 155, char: '無', sound: '없을', meaning: '무' },
  { id: 156, char: '聞', sound: '들을', meaning: '문' },
  { id: 157, char: '問', sound: '물을', meaning: '문' },
  { id: 158, char: '物', sound: '물건', meaning: '물' },
  { id: 159, char: '米', sound: '쌀', meaning: '미' },
  { id: 160, char: '民', sound: '백성', meaning: '민' },
  { id: 161, char: '班', sound: '나눌', meaning: '반' },
  { id: 162, char: '半', sound: '절반', meaning: '반' },
  { id: 163, char: '放', sound: '놓을', meaning: '방' },
  { id: 164, char: '番', sound: '차례', meaning: '번' },
  { id: 165, char: '別', sound: '다를', meaning: '별' },
  { id: 166, char: '步', sound: '걸음', meaning: '보' },
  { id: 167, char: '部', sound: '거느릴', meaning: '부' },
  { id: 168, char: '分', sound: '나눌', meaning: '분' },
  { id: 169, char: '社', sound: '모일', meaning: '사' },
  { id: 170, char: '事', sound: '일', meaning: '사' },
  { id: 171, char: '死', sound: '죽을', meaning: '사' },
  { id: 172, char: '色', sound: '빛', meaning: '색' },
  { id: 173, char: '書', sound: '글', meaning: '서' },
  { id: 174, char: '線', sound: '줄', meaning: '선' },
  { id: 175, char: '性', sound: '성품', meaning: '성' },
  { id: 176, char: '成', sound: '이룰', meaning: '성' },
  { id: 177, char: '所', sound: '바', meaning: '소' },
  { id: 178, char: '首', sound: '머리', meaning: '수' },
  { id: 179, char: '詩', sound: '글', meaning: '시' },
  { id: 180, char: '時', sound: '때', meaning: '시' },
  { id: 181, char: '示', sound: '보일', meaning: '시' },
  { id: 182, char: '市', sound: '저자', meaning: '시' },
  { id: 183, char: '植', sound: '심을', meaning: '식' },
  { id: 184, char: '神', sound: '귀신', meaning: '신' },
  { id: 185, char: '身', sound: '몸', meaning: '신' },
  { id: 186, char: '信', sound: '믿을', meaning: '신' },
  { id: 187, char: '新', sound: '새로울', meaning: '신' },
  { id: 188, char: '室', sound: '집', meaning: '실' },
  { id: 189, char: '安', sound: '편안할', meaning: '안' },
  { id: 190, char: '夜', sound: '밤', meaning: '야' },
  { id: 191, char: '弱', sound: '약할', meaning: '약' },
  { id: 192, char: '語', sound: '말씀', meaning: '어' },
  { id: 193, char: '言', sound: '말씀', meaning: '언' },
  { id: 194, char: '永', sound: '길', meaning: '영' },
  { id: 195, char: '英', sound: '꽃부리', meaning: '영' },
  { id: 196, char: '午', sound: '낮', meaning: '오' },
  { id: 197, char: '用', sound: '쓸', meaning: '용' },
  { id: 198, char: '友', sound: '벗', meaning: '우' },
  { id: 199, char: '遠', sound: '멀', meaning: '원' },
  { id: 200, char: '原', sound: '언덕,근본', meaning: '원' },
  { id: 201, char: '元', sound: '으뜸', meaning: '원' },
  { id: 202, char: '有', sound: '있을', meaning: '유' },
  { id: 203, char: '肉', sound: '고기', meaning: '육' },
  { id: 204, char: '育', sound: '기를', meaning: '육' },
  { id: 205, char: '銀', sound: '은', meaning: '은' },
  { id: 206, char: '音', sound: '소리', meaning: '음' },
  { id: 207, char: '邑', sound: '고을', meaning: '읍' },
  { id: 208, char: '意', sound: '뜻', meaning: '의' },
  { id: 209, char: '作', sound: '지을', meaning: '작' },
  { id: 210, char: '長', sound: '긴', meaning: '장' },
  { id: 211, char: '場', sound: '마당', meaning: '장' },
  { id: 212, char: '才', sound: '재주', meaning: '재' },
  { id: 213, char: '田', sound: '밭', meaning: '전' },
  { id: 214, char: '電', sound: '번개', meaning: '전' },
  { id: 215, char: '前', sound: '앞', meaning: '전' },
  { id: 216, char: '全', sound: '온전할', meaning: '전' },
  { id: 217, char: '朝', sound: '아침', meaning: '조' },
  { id: 218, char: '祖', sound: '할아비', meaning: '조' },
  { id: 219, char: '晝', sound: '낮', meaning: '주' },
  { id: 220, char: '住', sound: '살', meaning: '주' },
  { id: 221, char: '竹', sound: '대', meaning: '죽' },
  { id: 222, char: '重', sound: '무거울', meaning: '중' },
  { id: 223, char: '直', sound: '곧을', meaning: '직' },
  { id: 224, char: '草', sound: '풀', meaning: '초' },
  { id: 225, char: '村', sound: '마을', meaning: '촌' },
  { id: 226, char: '秋', sound: '가을', meaning: '추' },
  { id: 227, char: '春', sound: '봄', meaning: '춘' },
  { id: 228, char: '親', sound: '친할', meaning: '친' },
  { id: 229, char: '太', sound: '클', meaning: '태' },
  { id: 230, char: '通', sound: '통할', meaning: '통' },
  { id: 231, char: '貝', sound: '조개', meaning: '패' },
  { id: 232, char: '便', sound: '편할', meaning: '편' },
  { id: 233, char: '平', sound: '평평할', meaning: '평' },
  { id: 234, char: '夏', sound: '여름', meaning: '하' },
  { id: 235, char: '學', sound: '배울', meaning: '학' },
  { id: 236, char: '韓', sound: '나라이름', meaning: '한' },
  { id: 237, char: '漢', sound: '한수', meaning: '한' },
  { id: 238, char: '合', sound: '합할', meaning: '합' },
  { id: 239, char: '海', sound: '바다', meaning: '해' },
  { id: 240, char: '行', sound: '다닐', meaning: '행' },
  { id: 241, char: '血', sound: '피', meaning: '혈' },
  { id: 242, char: '形', sound: '모양', meaning: '형' },
  { id: 243, char: '花', sound: '꽃', meaning: '화' },
  { id: 244, char: '話', sound: '말씀', meaning: '화' },
  { id: 245, char: '和', sound: '화할,화목할', meaning: '화' },
  { id: 246, char: '活', sound: '살', meaning: '활' },
  { id: 247, char: '黃', sound: '누를', meaning: '황' },
  { id: 248, char: '會', sound: '모일', meaning: '회' },
  { id: 249, char: '孝', sound: '효도', meaning: '효' },
  { id: 250, char: '後', sound: '뒤', meaning: '후' }
];

// ----------------------------------------------------------------------
// [PART 2] 교과서 한자어 데이터 (독음 조립 퍼즐 게임용)
// ----------------------------------------------------------------------
export const WORDS_TEXTBOOK_8 = [
  { id: 1, word: "제형", hanja: "弟兄", reading: "제형", syllables: ["제", "형"], hanjaChars: ["弟", "兄"], example: "그 두 사람은 피로 맺어진 제형처럼 서로를 아끼며 지냈다." },
  { id: 2, word: "칠십", hanja: "七十", reading: "칠십", syllables: ["칠", "십"], hanjaChars: ["七", "十"], example: "할아버지는 올해로 칠십이 되셨다." },
  { id: 3, word: "자녀", hanja: "子女", reading: "자녀", syllables: ["자", "녀"], hanjaChars: ["子", "女"], example: "부모는 자녀의 행복을 가장 중요하게 생각한다." },
  { id: 4, word: "남북", hanja: "南北", reading: "남북", syllables: ["남", "북"], hanjaChars: ["南", "北"], example: "남북은 오랜 시간 동안 분단된 상태로 이어져 왔다." },
  { id: 5, word: "일남", hanja: "一男", reading: "일남", syllables: ["일", "남"], hanjaChars: ["一", "男"], example: "그 집은 일남 이녀로 모두 세 자녀를 두고 있다." },
  { id: 6, word: "서토", hanja: "西土", reading: "서토", syllables: ["서", "토"], hanjaChars: ["西", "土"], example: "황해도와 평안도를 예전에는 서토라고 부르기도 했다." },
  { id: 7, word: "부자", hanja: "父子", reading: "부자", syllables: ["부", "자"], hanjaChars: ["父", "子"], example: "그들은 부자 사이가 매우 각별했다." },
  { id: 8, word: "오월", hanja: "五月", reading: "오월", syllables: ["오", "월"], hanjaChars: ["五", "月"], example: "오월에는 날씨가 따뜻해져 야외 활동을 하기 좋다." },
  { id: 9, word: "북인", hanja: "北人", reading: "북인", syllables: ["북", "인"], hanjaChars: ["北", "人"], example: "조선 시대에는 정치 세력 중 하나로 북인이 있었다." },
  { id: 10, word: "남인", hanja: "南人", reading: "남인", syllables: ["남", "인"], hanjaChars: ["南", "人"], example: "남인은 조선 중기의 대표적인 사색당파 중 하나였다." },
  { id: 11, word: "이십", hanja: "二十", reading: "이십", syllables: ["이", "십"], hanjaChars: ["二", "十"], example: "시험 문제는 모두 이십 문항으로 구성되어 있다." },
  { id: 12, word: "토목", hanja: "土木", reading: "토목", syllables: ["토", "목"], hanjaChars: ["土", "木"], example: "그는 대학에서 토목 공학을 전공했다." },
  { id: 13, word: "제자", hanja: "弟子", reading: "제자", syllables: ["제", "자"], hanjaChars: ["弟", "子"], example: "스승은 제자들에게 바른 삶의 태도를 가르쳤다." },
  { id: 14, word: "부모", hanja: "父母", reading: "부모", syllables: ["부", "모"], hanjaChars: ["父", "母"], example: "부모의 사랑은 무엇과도 비교할 수 없다." }
];

export const WORDS_TEXTBOOK_7 = [
  { id: 1, word: "대인", hanja: "大人", reading: "대인", syllables: ["대", "인"], hanjaChars: ["大", "人"], example: "그는 언제나 대인다운 품위 있는 태도를 보였다." },
  { id: 2, word: "거인", hanja: "巨人", reading: "거인", syllables: ["거", "인"], hanjaChars: ["巨", "人"], example: "전설 속 거인은 산만큼이나 크게 묘사된다." },
  { id: 3, word: "성인", hanja: "成人", reading: "성인", syllables: ["성", "인"], hanjaChars: ["成", "人"], example: "법적으로 성인이 되면 스스로 책임을 져야 한다." },
  { id: 4, word: "군자", hanja: "君子", reading: "군자", syllables: ["군", "자"], hanjaChars: ["君", "子"], example: "군자는 말보다 행동으로 신뢰를 쌓는다." },
  { id: 5, word: "신분", hanja: "身分", reading: "신분", syllables: ["신", "분"], hanjaChars: ["身", "分"], example: "그는 자신의 신분을 숨기고 조용히 여행했다." },
  { id: 6, word: "지위", hanja: "地位", reading: "지위", syllables: ["지", "위"], hanjaChars: ["地", "位"], example: "높은 지위에 있을수록 책임도 커진다." },
  { id: 7, word: "관직", hanja: "官職", reading: "관직", syllables: ["관", "직"], hanjaChars: ["官", "職"], example: "그는 오랜 공로를 인정받아 중요한 관직에 올랐다." },
  { id: 8, word: "입출", hanja: "入出", reading: "입출", syllables: ["입", "출"], hanjaChars: ["入", "出"], example: "회계 장부에는 매달 입출 내역이 기록된다." },
  { id: 9, word: "수하", hanja: "手下", reading: "수하", syllables: ["수", "하"], hanjaChars: ["手", "下"], example: "그는 믿을 만한 수하 몇 명과 함께 움직였다." },
  { id: 10, word: "문제", hanja: "門弟", reading: "문제", syllables: ["문", "제"], hanjaChars: ["門", "弟"], example: "그는 스승의 문제로서 예의를 소중히 여겼다." },
  { id: 11, word: "하산", hanja: "下山", reading: "하산", syllables: ["하", "산"], hanjaChars: ["下", "山"], example: "해가 지기 전에 모두 하산을 마쳤다." },
  { id: 12, word: "강서", hanja: "江西", reading: "강서", syllables: ["강", "서"], hanjaChars: ["江", "西"], example: "그 마을은 강서 지역에 자리 잡고 있다." },
  { id: 13, word: "시월", hanja: "十月", reading: "시월", syllables: ["시", "월"], hanjaChars: ["十", "月"], example: "시월이 되자 날씨가 한결 선선해졌다." },
  { id: 14, word: "강상", hanja: "江上", reading: "강상", syllables: ["강", "상"], hanjaChars: ["江", "上"], example: "배는 천천히 강상으로 떠올랐다." },
  { id: 15, word: "수족", hanja: "手足", reading: "수족", syllables: ["수", "족"], hanjaChars: ["手", "足"], example: "그는 부하들을 자신의 수족처럼 믿고 맡겼다." },
  { id: 16, word: "북서", hanja: "北西", reading: "북서", syllables: ["북", "서"], hanjaChars: ["北", "西"], example: "바람이 북서쪽에서 불어왔다." },
  { id: 17, word: "출토", hanja: "出土", reading: "출토", syllables: ["출", "토"], hanjaChars: ["出", "土"], example: "유적지에서 오래된 유물이 출토되었다." },
  { id: 18, word: "출", hanja: "出", reading: "출", syllables: ["출"], hanjaChars: ["出"], example: "입구와 출을 잘 구분해야 한다." },
  { id: 19, word: "동남", hanja: "東南", reading: "동남", syllables: ["동", "남"], hanjaChars: ["東", "南"], example: "학교는 마을의 동남쪽에 위치해 있다." },
  { id: 20, word: "부모", hanja: "父母", reading: "부모", syllables: ["부", "모"], hanjaChars: ["父", "母"], example: "부모의 사랑은 언제나 깊고 변함없다." },
  { id: 21, word: "일금", hanja: "一金", reading: "일금", syllables: ["일", "금"], hanjaChars: ["一", "金"], example: "일금 삼만 원을 용돈으로 받았다." }
];

export const WORDS_TEXTBOOK_6 = [
  { id: 1, word: "형제", hanja: "兄弟", reading: "형제", syllables: ["형", "제"], hanjaChars: ["兄", "弟"], example: "형제는 서로 도우며 자라야 한다." },
  { id: 2, word: "수족", hanja: "手足", reading: "수족", syllables: ["수", "족"], hanjaChars: ["手", "足"], example: "그는 믿을 만한 사람을 수족처럼 부렸다." },
  { id: 3, word: "육십", hanja: "六十", reading: "육십", syllables: ["육", "십"], hanjaChars: ["六", "十"], example: "조부는 올해 육십을 넘기셨다." },
  { id: 4, word: "천마", hanja: "天馬", reading: "천마", syllables: ["천", "마"], hanjaChars: ["天", "馬"], example: "그의 상상력은 천마처럼 자유로웠다." },
  { id: 5, word: "임목", hanja: "林木", reading: "임목", syllables: ["임", "목"], hanjaChars: ["林", "木"], example: "산의 임목을 체계적으로 관리해야 한다." },
  { id: 6, word: "팔목", hanja: "八目", reading: "팔목", syllables: ["팔", "목"], hanjaChars: ["八", "目"], example: "옛 놀이 중에는 팔목이라는 것도 있었다." },
  { id: 7, word: "출마", hanja: "出馬", reading: "출마", syllables: ["출", "마"], hanjaChars: ["出", "馬"], example: "그는 이번 선거에 출마했다." },
  { id: 8, word: "삼남", hanja: "三南", reading: "삼남", syllables: ["삼", "남"], hanjaChars: ["三", "南"], example: "삼남 지방은 예부터 곡창 지대였다." },
  { id: 9, word: "인마", hanja: "人馬", reading: "인마", syllables: ["인", "마"], hanjaChars: ["人", "馬"], example: "전쟁에는 많은 인마가 동원되었다." },
  { id: 10, word: "토석", hanja: "土石", reading: "토석", syllables: ["토", "석"], hanjaChars: ["土", "石"], example: "공사 현장에 토석이 쌓여 있었다." },
  { id: 11, word: "월출", hanja: "月出", reading: "월출", syllables: ["월", "출"], hanjaChars: ["月", "出"], example: "바다 위로 아름다운 월출이 보였다." },
  { id: 12, word: "청산", hanja: "靑山", reading: "청산", syllables: ["청", "산"], hanjaChars: ["靑", "山"], example: "멀리 청산이 겹겹이 이어졌다." },
  { id: 13, word: "금문", hanja: "金門", reading: "금문", syllables: ["금", "문"], hanjaChars: ["金", "門"], example: "궁궐의 금문이 웅장하게 서 있었다." },
  { id: 14, word: "북상", hanja: "北上", reading: "북상", syllables: ["북", "상"], hanjaChars: ["北", "上"], example: "태풍이 점점 북상하고 있다." },
  { id: 15, word: "내외", hanja: "內外", reading: "내외", syllables: ["내", "외"], hanjaChars: ["內", "外"], example: "행사에는 내외 귀빈이 참석했다." },
  { id: 16, word: "토족", hanja: "土足", reading: "토족", syllables: ["토", "족"], hanjaChars: ["土", "足"], example: "집 안에는 토족으로 들어오지 마라." },
  { id: 17, word: "수중", hanja: "水中", reading: "수중", syllables: ["수", "중"], hanjaChars: ["水", "中"], example: "물고기는 수중에서 숨을 쉰다." },
  { id: 18, word: "삼천", hanja: "三千", reading: "삼천", syllables: ["삼", "천"], hanjaChars: ["三", "千"], example: "우리나라 금수강산 삼천 리." },
  { id: 19, word: "백옥", hanja: "白玉", reading: "백옥", syllables: ["백", "옥"], hanjaChars: ["白", "玉"], example: "그의 피부는 백옥처럼 희었다." },
  { id: 20, word: "이남", hanja: "二男", reading: "이남", syllables: ["이", "남"], hanjaChars: ["二", "男"], example: "그는 집안의 이남이다." },
  { id: 21, word: "이년", hanja: "二年", reading: "이년", syllables: ["이", "년"], hanjaChars: ["二", "年"], example: "이년 동안 준비한 결과였다." },
  { id: 22, word: "일출", hanja: "日出", reading: "일출", syllables: ["일", "출"], hanjaChars: ["日", "出"], example: "산 정상에서 일출을 보았다." },
  { id: 23, word: "문중", hanja: "門中", reading: "문중", syllables: ["문", "중"], hanjaChars: ["門", "中"], example: "문중의 어른들께 인사를 드렸다." },
  { id: 24, word: "문내", hanja: "門內", reading: "문내", syllables: ["문", "내"], hanjaChars: ["門", "內"], example: "문내 사람들만 모이는 자리였다." },
  { id: 25, word: "육", hanja: "六", reading: "육", syllables: ["육"], hanjaChars: ["六"], example: "주사위에는 육까지의 숫자가 있다." },
  { id: 26, word: "문하생", hanja: "門下生", reading: "문하생", syllables: ["문", "하", "생"], hanjaChars: ["門", "下", "生"], example: "그는 유명 학자의 문하생이었다." },
  { id: 27, word: "동해", hanja: "東海", reading: "동해", syllables: ["동", "해"], hanjaChars: ["東", "海"], example: "동해의 일출은 장관이다." },
  { id: 28, word: "출입", hanja: "出入", reading: "출입", syllables: ["출", "입"], hanjaChars: ["出", "入"], example: "외부인의 출입을 통제한다." },
  { id: 29, word: "남자", hanja: "男子", reading: "남자", syllables: ["남", "자"], hanjaChars: ["男", "子"], example: "그는 씩씩한 남자였다." },
  { id: 30, word: "백성", hanja: "百姓", reading: "백성", syllables: ["백", "성"], hanjaChars: ["百", "姓"], example: "임금은 백성을 먼저 생각해야 한다." },
  { id: 31, word: "유월", hanja: "六月", reading: "유월", syllables: ["유", "월"], hanjaChars: ["六", "月"], example: "유월에는 장마가 시작된다." },
  { id: 32, word: "목하", hanja: "目下", reading: "목하", syllables: ["목", "하"], hanjaChars: ["目", "下"], example: "목하 가장 중요한 과제다." },
  { id: 33, word: "백구", hanja: "百口", reading: "백구", syllables: ["백", "구"], hanjaChars: ["百", "口"], example: "그 집은 백구가 넘는 대가족이다." },
  { id: 34, word: "인중", hanja: "人中", reading: "인중", syllables: ["인", "중"], hanjaChars: ["人", "中"], example: "인중이 깊으면 복이 많다고 한다." },
  { id: 35, word: "모자", hanja: "母子", reading: "모자", syllables: ["모", "자"], hanjaChars: ["母", "子"], example: "모자 사이는 각별했다." },
  { id: 36, word: "소문", hanja: "小門", reading: "소문", syllables: ["소", "문"], hanjaChars: ["小", "門"], example: "뒤뜰에는 작은 소문이 있었다." },
  { id: 37, word: "여심", hanja: "女心", reading: "여심", syllables: ["여", "심"], hanjaChars: ["女", "心"], example: "여심을 사로잡는 말이었다." },
  { id: 38, word: "선금", hanja: "先金", reading: "선금", syllables: ["선", "금"], hanjaChars: ["先", "金"], example: "계약 시 선금을 지불했다." },
  { id: 39, word: "일출", hanja: "日出", reading: "일출", syllables: ["일", "출"], hanjaChars: ["日", "出"], example: "일출을 보기 위해 새벽에 일어났다." },
  { id: 40, word: "삼남", hanja: "三男", reading: "삼남", syllables: ["삼", "남"], hanjaChars: ["三", "男"], example: "그는 집안의 삼남이다." },
  { id: 41, word: "인화", hanja: "人火", reading: "인화", syllables: ["인", "화"], hanjaChars: ["人", "火"], example: "이번 화재는 인화로 밝혀졌다." },
  { id: 42, word: "하수", hanja: "下手", reading: "하수", syllables: ["하", "수"], hanjaChars: ["下", "手"], example: "그는 아직 그 분야의 하수이다." },
  { id: 43, word: "문중", hanja: "門中", reading: "문중", syllables: ["문", "중"], hanjaChars: ["門", "中"], example: "문중 회의가 열렸다." },
  { id: 44, word: "청백", hanja: "靑白", reading: "청백", syllables: ["청", "백"], hanjaChars: ["靑", "白"], example: "청백의 대비가 뚜렷했다." },
  { id: 45, word: "인목", hanja: "人目", reading: "인목", syllables: ["인", "목"], hanjaChars: ["人", "目"], example: "인목을 의식하지 않을 수 없었다." },
  { id: 46, word: "임지", hanja: "林地", reading: "임지", syllables: ["임", "지"], hanjaChars: ["林", "地"], example: "임지는 산림 보호의 대상이다." },
  { id: 47, word: "대천", hanja: "大川", reading: "대천", syllables: ["대", "천"], hanjaChars: ["大", "川"], example: "대천을 건너는 배가 보였다." },
  { id: 48, word: "연중", hanja: "年中", reading: "연중", syllables: ["연", "중"], hanjaChars: ["年", "中"], example: "연중 가장 바쁜 시기다." },
  { id: 49, word: "시월", hanja: "十月", reading: "시월", syllables: ["시", "월"], hanjaChars: ["十", "月"], example: "시월의 하늘은 높고 맑다." },
  { id: 50, word: "좌수", hanja: "左手", reading: "좌수", syllables: ["좌", "수"], hanjaChars: ["左", "手"], example: "좌수로는 글씨를 잘 쓰지 못한다." },
  { id: 51, word: "우수", hanja: "右手", reading: "우수", syllables: ["우", "수"], hanjaChars: ["右", "手"], example: "그는 우수를 주로 사용한다." },
  { id: 52, word: "삼삼오오", hanja: "三三五五", reading: "삼삼오오", syllables: ["삼", "삼", "오", "오"], hanjaChars: ["三", "三", "五", "五"], example: "사람들이 삼삼오오 모여 이야기를 나눴다." }
];

export const WORDS_TEXTBOOK_5_JUN = [
  { id: 1, word: "명차", hanja: "名車", reading: "명차", syllables: ["명", "차"], hanjaChars: ["名", "車"], example: "이 박물관에는 세계적인 명차들이 전시되어 있다." },
  { id: 2, word: "마력", hanja: "馬力", reading: "마력", syllables: ["마", "력"], hanjaChars: ["馬", "力"], example: "이 자동차는 강한 마력을 자랑한다." },
  { id: 3, word: "동문", hanja: "東門", reading: "동문", syllables: ["동", "문"], hanjaChars: ["東", "門"], example: "성곽의 동문이 웅장하게 서 있다." },
  { id: 4, word: "소년", hanja: "少年", reading: "소년", syllables: ["소", "년"], hanjaChars: ["少", "年"], example: "소년은 미래의 꿈을 키운다." },
  { id: 5, word: "고본", hanja: "古本", reading: "고본", syllables: ["고", "본"], hanjaChars: ["古", "本"], example: "도서관에서 귀한 고본을 발견했다." },
  { id: 6, word: "우수", hanja: "右手", reading: "우수", syllables: ["우", "수"], hanjaChars: ["右", "手"], example: "그는 우수를 주로 사용한다." },
  { id: 7, word: "토목", hanja: "土木", reading: "토목", syllables: ["토", "목"], hanjaChars: ["土", "木"], example: "이 지역에서는 토목 공사가 진행 중이다." },
  { id: 8, word: "문내", hanja: "門內", reading: "문내", syllables: ["문", "내"], hanjaChars: ["門", "內"], example: "문내 관계자만 출입할 수 있다." },
  { id: 9, word: "석화", hanja: "石火", reading: "석화", syllables: ["석", "화"], hanjaChars: ["石", "火"], example: "돌이 부딪치며 석화가 튀었다." },
  { id: 10, word: "문사", hanja: "文士", reading: "문사", syllables: ["문", "사"], hanjaChars: ["文", "士"], example: "그는 이름난 문사로 존경받았다." },
  { id: 11, word: "주인", hanja: "主人", reading: "주인", syllables: ["주", "인"], hanjaChars: ["主", "人"], example: "가게 주인이 손님을 맞이했다." },
  { id: 12, word: "선생", hanja: "先生", reading: "선생", syllables: ["선", "생"], hanjaChars: ["先", "生"], example: "선생의 가르침을 항상 기억한다." },
  { id: 13, word: "하위", hanja: "下位", reading: "하위", syllables: ["하", "위"], hanjaChars: ["下", "位"], example: "그는 하위 단계부터 시작했다." },
  { id: 14, word: "말일", hanja: "末日", reading: "말일", syllables: ["말", "일"], hanjaChars: ["末", "日"], example: "월 말일에 정산이 있다." },
  { id: 15, word: "자모", hanja: "字母", reading: "자모", syllables: ["자", "모"], hanjaChars: ["字", "母"], example: "한글은 자모의 조합으로 이루어진다." },
  { id: 16, word: "천금", hanja: "千金", reading: "천금", syllables: ["천", "금"], hanjaChars: ["千", "金"], example: "이 기회는 천금과도 같다." },
  { id: 17, word: "북어", hanja: "北魚", reading: "북어", syllables: ["북", "어"], hanjaChars: ["北", "魚"], example: "국에 북어를 넣어 끓였다." },
  { id: 18, word: "부녀", hanja: "父女", reading: "부녀", syllables: ["부", "녀"], hanjaChars: ["父", "女"], example: "부녀가 함께 길을 걷고 있다." },
  { id: 19, word: "이목", hanja: "耳目", reading: "이목", syllables: ["이", "목"], hanjaChars: ["耳", "目"], example: "모두의 이목이 그에게 집중되었다." },
  { id: 20, word: "고금", hanja: "古今", reading: "고금", syllables: ["고", "금"], hanjaChars: ["古", "今"], example: "고금을 막론하고 진리는 같다." },
  { id: 21, word: "산남", hanja: "山南", reading: "산남", syllables: ["산", "남"], hanjaChars: ["山", "南"], example: "집이 산남에 있어 볕이 잘 든다." },
  { id: 22, word: "사방", hanja: "四方", reading: "사방", syllables: ["사", "방"], hanjaChars: ["四", "方"], example: "사방이 훤히 트여 있다." },
  { id: 23, word: "출력", hanja: "出力", reading: "출력", syllables: ["출", "력"], hanjaChars: ["出", "力"], example: "프린터로 문서를 출력했다." },
  { id: 24, word: "입력", hanja: "入力", reading: "입력", syllables: ["입", "력"], hanjaChars: ["入", "力"], example: "비밀번호를 정확히 입력했다." },
  { id: 25, word: "옥의옥식", hanja: "玉衣玉食", reading: "옥의옥식", syllables: ["옥", "의", "옥", "식"], hanjaChars: ["玉", "衣", "玉", "食"], example: "사람들은 옥의옥식을 동경한다." },
  { id: 26, word: "세상", hanja: "世上", reading: "세상", syllables: ["세", "상"], hanjaChars: ["世", "上"], example: "세상에는 다양한 사람들이 있다." },
  { id: 27, word: "남녀", hanja: "男女", reading: "남녀", syllables: ["남", "녀"], hanjaChars: ["男", "女"], example: "남녀 모두에게 기회가 주어졌다." },
  { id: 28, word: "부족", hanja: "不足", reading: "부족", syllables: ["부", "족"], hanjaChars: ["不", "足"], example: "아직 경험이 부족하다." },
  { id: 29, word: "우이", hanja: "右耳", reading: "우이", syllables: ["우", "이"], hanjaChars: ["右", "耳"], example: "우이에 소리가 잘 들리지 않았다." },
  { id: 30, word: "부정", hanja: "不正", reading: "부정", syllables: ["부", "정"], hanjaChars: ["不", "正"], example: "부정한 행동은 금지된다." },
  { id: 31, word: "북서", hanja: "北西", reading: "북서", syllables: ["북", "서"], hanjaChars: ["北", "西"], example: "바람이 북서쪽에서 불어온다." },
  { id: 32, word: "청목", hanja: "靑木", reading: "청목", syllables: ["청", "목"], hanjaChars: ["靑", "木"], example: "청목으로 물들인 천이다." },
  { id: 33, word: "하산", hanja: "下山", reading: "하산", syllables: ["하", "산"], hanjaChars: ["下", "山"], example: "해 지기 전에 하산했다." },
  { id: 34, word: "월말", hanja: "月末", reading: "월말", syllables: ["월", "말"], hanjaChars: ["月", "末"], example: "월말에 보고서를 제출한다." },
  { id: 35, word: "북문", hanja: "北門", reading: "북문", syllables: ["북", "문"], hanjaChars: ["北", "門"], example: "성의 북문을 지나갔다." },
  { id: 36, word: "역사", hanja: "力士", reading: "역사", syllables: ["역", "사"], hanjaChars: ["力", "士"], example: "그는 힘이 센 역사였다." },
  { id: 37, word: "대왕", hanja: "大王", reading: "대왕", syllables: ["대", "왕"], hanjaChars: ["大", "王"], example: "세종 대왕은 위대한 임금이다." },
  { id: 38, word: "소자", hanja: "小子", reading: "소자", syllables: ["소", "자"], hanjaChars: ["小", "子"], example: "소자는 감히 여쭙니다." },
  { id: 39, word: "백성", hanja: "百姓", reading: "백성", syllables: ["백", "성"], hanjaChars: ["百", "姓"], example: "임금은 백성을 위해야 한다." },
  { id: 40, word: "외향", hanja: "外向", reading: "외향", syllables: ["외", "향"], hanjaChars: ["外", "向"], example: "그는 외향적인 성격이다." },
  { id: 41, word: "자기", hanja: "自己", reading: "자기", syllables: ["자", "기"], hanjaChars: ["自", "己"], example: "자기를 믿는 것이 중요하다." },
  { id: 42, word: "입금", hanja: "入金", reading: "입금", syllables: ["입", "금"], hanjaChars: ["入", "金"], example: "월급이 통장에 입금되었다." },
  { id: 43, word: "방향", hanja: "方向", reading: "방향", syllables: ["방", "향"], hanjaChars: ["方", "向"], example: "방향을 잘못 잡았다." },
  { id: 44, word: "강심", hanja: "江心", reading: "강심", syllables: ["강", "심"], hanjaChars: ["江", "心"], example: "배가 강심으로 나아갔다." },
  { id: 45, word: "금일", hanja: "今日", reading: "금일", syllables: ["금", "일"], hanjaChars: ["今", "日"], example: "금일 회의는 여기까지입니다." },
  { id: 46, word: "대지", hanja: "大地", reading: "대지", syllables: ["대", "지"], hanjaChars: ["大", "地"], example: "비가 대지를 적셨다." },
  { id: 47, word: "우양", hanja: "牛羊", reading: "우양", syllables: ["우", "양"], hanjaChars: ["牛", "羊"], example: "초원에 우양이 풀을 뜯고 있다." },
  { id: 48, word: "연상", hanja: "年上", reading: "연상", syllables: ["연", "상"], hanjaChars: ["年", "上"], example: "그는 나보다 연상이다." },
  { id: 49, word: "연하", hanja: "年下", reading: "연하", syllables: ["연", "하"], hanjaChars: ["年", "下"], example: "연하의 동생과 친하다." },
  { id: 50, word: "명산대천", hanja: "名山大川", reading: "명산대천", syllables: ["명", "산", "대", "천"], hanjaChars: ["名", "山", "大", "川"], example: "명산대천을 두루 여행했다." },
  { id: 51, word: "동서고금", hanja: "東西古今", reading: "동서고금", syllables: ["동", "서", "고", "금"], hanjaChars: ["東", "西", "古", "今"], example: "동서고금의 지혜가 담긴 책이다." }
];

export const WORDS_TEXTBOOK_5 = [
  { id: 1, word: "농촌", hanja: "農村", reading: "농촌", syllables: ["농", "촌"], hanjaChars: ["農", "村"], example: "농촌에서는 주로 농업에 종사한다." },
  { id: 2, word: "남촌", hanja: "南村", reading: "남촌", syllables: ["남", "촌"], hanjaChars: ["南", "村"], example: "조선 시대에는 서울의 남쪽을 남촌이라 불렀다." },
  { id: 3, word: "촌부", hanja: "村夫", reading: "촌부", syllables: ["촌", "부"], hanjaChars: ["村", "夫"], example: "촌부의 소박한 삶이 그려졌다." },
  { id: 4, word: "어패", hanja: "魚貝", reading: "어패", syllables: ["어", "패"], hanjaChars: ["魚", "貝"], example: "시장에서 신선한 어패를 샀다." },
  { id: 5, word: "사리", hanja: "事理", reading: "사리", syllables: ["사", "리"], hanjaChars: ["事", "理"], example: "일의 사리를 따져 판단해야 한다." },
  { id: 6, word: "대리", hanja: "代理", reading: "대리", syllables: ["대", "리"], hanjaChars: ["代", "理"], example: "그는 회의에 대리로 참석했다." },
  { id: 7, word: "매번", hanja: "每番", reading: "매번", syllables: ["매", "번"], hanjaChars: ["每", "番"], example: "매번 같은 실수를 반복했다." },
  { id: 8, word: "성명", hanja: "姓名", reading: "성명", syllables: ["성", "명"], hanjaChars: ["姓", "名"], example: "신청서에 성명을 적어 주세요." },
  { id: 9, word: "정신", hanja: "正信", reading: "정신", syllables: ["정", "신"], hanjaChars: ["正", "信"], example: "올바른 정신을 지니는 것이 중요하다." },
  { id: 10, word: "두목", hanja: "頭目", reading: "두목", syllables: ["두", "목"], hanjaChars: ["頭", "目"], example: "그 무리의 두목이 붙잡혔다." },
  { id: 11, word: "명백", hanja: "明白", reading: "명백", syllables: ["명", "백"], hanjaChars: ["明", "白"], example: "사실이 명백히 드러났다." },
  { id: 12, word: "가수", hanja: "歌手", reading: "가수", syllables: ["가", "수"], hanjaChars: ["歌", "手"], example: "그 가수는 노래 실력이 뛰어나다." },
  { id: 13, word: "본말", hanja: "本末", reading: "본말", syllables: ["본", "말"], hanjaChars: ["本", "末"], example: "일의 본말을 잘 파악해야 한다." },
  { id: 14, word: "자제", hanja: "子弟", reading: "자제", syllables: ["자", "제"], hanjaChars: ["子", "弟"], example: "그는 남의 자제를 예의 바르게 대했다." },
  { id: 15, word: "견본", hanja: "見本", reading: "견본", syllables: ["견", "본"], hanjaChars: ["見", "本"], example: "상품 견본을 확인했다." },
  { id: 16, word: "지구", hanja: "地區", reading: "지구", syllables: ["지", "구"], hanjaChars: ["地", "區"], example: "이 지구는 개발 제한 구역이다." },
  { id: 17, word: "정서", hanja: "正書", reading: "정서", syllables: ["정", "서"], hanjaChars: ["正", "書"], example: "글씨를 정서로 바르게 썼다." },
  { id: 18, word: "수기", hanja: "手記", reading: "수기", syllables: ["수", "기"], hanjaChars: ["手", "記"], example: "그는 자신의 경험을 수기로 남겼다." },
  { id: 19, word: "북해", hanja: "北海", reading: "북해", syllables: ["북", "해"], hanjaChars: ["北", "海"], example: "북해 유전이 개발되었다." },
  { id: 20, word: "기합", hanja: "氣合", reading: "기합", syllables: ["기", "합"], hanjaChars: ["氣", "合"], example: "태권도 수련 중 기합을 넣었다." },
  { id: 21, word: "양모", hanja: "羊毛", reading: "양모", syllables: ["양", "모"], hanjaChars: ["羊", "毛"], example: "양모로 만든 옷은 따뜻하다." },
  { id: 22, word: "부위", hanja: "部位", reading: "부위", syllables: ["부", "위"], hanjaChars: ["部", "位"], example: "다친 부위를 소독했다." },
  { id: 23, word: "차도", hanja: "車道", reading: "차도", syllables: ["차", "도"], hanjaChars: ["車", "道"], example: "차도로 내려가면 위험하다." },
  { id: 24, word: "학문", hanja: "學問", reading: "학문", syllables: ["학", "문"], hanjaChars: ["學", "問"], example: "학문에 힘쓰는 자세가 필요하다." },
  { id: 25, word: "만일", hanja: "萬一", reading: "만일", syllables: ["만", "일"], hanjaChars: ["萬", "一"], example: "만일의 사태에 대비했다." },
  { id: 26, word: "회사", hanja: "會社", reading: "회사", syllables: ["회", "사"], hanjaChars: ["會", "社"], example: "그는 큰 회사에 다닌다." },
  { id: 27, word: "남북", hanja: "南北", reading: "남북", syllables: ["남", "북"], hanjaChars: ["南", "北"], example: "남북의 기온 차이가 크다." },
  { id: 28, word: "남향", hanja: "南向", reading: "남향", syllables: ["남", "향"], hanjaChars: ["南", "向"], example: "이 집은 남향이라 볕이 좋다." },
  { id: 29, word: "자력", hanja: "自力", reading: "자력", syllables: ["자", "력"], hanjaChars: ["自", "力"], example: "자력으로 문제를 해결했다." },
  { id: 30, word: "국민", hanja: "國民", reading: "국민", syllables: ["국", "민"], hanjaChars: ["國", "民"], example: "국민의 권리와 의무가 있다." },
  { id: 31, word: "백성", hanja: "百姓", reading: "백성", syllables: ["백", "성"], hanjaChars: ["百", "姓"], example: "임금은 백성을 먼저 생각했다." },
  { id: 32, word: "주간", hanja: "晝間", reading: "주간", syllables: ["주", "간"], hanjaChars: ["晝", "間"], example: "주간에는 일을 하고 밤에는 쉰다." },
  { id: 33, word: "야간", hanja: "夜間", reading: "야간", syllables: ["야", "간"], hanjaChars: ["夜", "間"], example: "야간 운전은 조심해야 한다." },
  { id: 34, word: "구우일모", hanja: "九牛一毛", reading: "구우일모", syllables: ["구", "우", "일", "모"], hanjaChars: ["九", "牛", "一", "毛"], example: "그 성과는 전체에 비하면 구우일모에 불과하다." },
  { id: 35, word: "부모", hanja: "父母", reading: "부모", syllables: ["부", "모"], hanjaChars: ["父", "母"], example: "부모의 은혜를 잊지 말아야 한다." },
  { id: 36, word: "김구", hanja: "金九", reading: "김구", syllables: ["김", "구"], hanjaChars: ["金", "九"], example: "김구 선생은 독립운동가이다." },
  { id: 37, word: "연상", hanja: "蓮上", reading: "연상", syllables: ["연", "상"], hanjaChars: ["蓮", "上"], example: "그의 자는 연상이다." },
  { id: 38, word: "백범", hanja: "白凡", reading: "백범", syllables: ["백", "범"], hanjaChars: ["白", "凡"], example: "백범은 김구 선생의 호이다." },
  { id: 39, word: "연하", hanja: "蓮下", reading: "연하", syllables: ["연", "하"], hanjaChars: ["蓮", "下"], example: "연하는 김구의 또 다른 호이다." },
  { id: 40, word: "창수", hanja: "昌洙", reading: "창수", syllables: ["창", "수"], hanjaChars: ["昌", "洙"], example: "김구의 본명은 창수이다." },
  { id: 41, word: "상해", hanja: "上海", reading: "상해", syllables: ["상", "해"], hanjaChars: ["上", "海"], example: "상해에는 임시정부가 있었다." },
  { id: 42, word: "안두희", hanja: "安斗熙", reading: "안두희", syllables: ["안", "두", "희"], hanjaChars: ["安", "斗", "熙"], example: "안두희는 김구를 암살한 인물이다." },
  { id: 43, word: "수평", hanja: "水平", reading: "수평", syllables: ["수", "평"], hanjaChars: ["水", "平"], example: "탁자가 수평을 이루고 있다." },
  { id: 44, word: "평화", hanja: "平和", reading: "평화", syllables: ["평", "화"], hanjaChars: ["平", "和"], example: "세계의 평화를 기원한다." },
  { id: 45, word: "불평", hanja: "不平", reading: "불평", syllables: ["불", "평"], hanjaChars: ["不", "平"], example: "그는 작은 일에도 불평이 많다." },
  { id: 46, word: "별명", hanja: "別名", reading: "별명", syllables: ["별", "명"], hanjaChars: ["別", "名"], example: "그에게는 재미있는 별명이 있다." },
  { id: 47, word: "문학", hanja: "文學", reading: "문학", syllables: ["문", "학"], hanjaChars: ["文", "學"], example: "문학 작품을 감상했다." },
  { id: 48, word: "하직", hanja: "下直", reading: "하직", syllables: ["하", "직"], hanjaChars: ["下", "直"], example: "먼 길을 떠나며 어른께 하직했다." },
  { id: 49, word: "구내", hanja: "區內", reading: "구내", syllables: ["구", "내"], hanjaChars: ["區", "內"], example: "구내 식당을 이용했다." },
  { id: 50, word: "개소", hanja: "開所", reading: "개소", syllables: ["개", "소"], hanjaChars: ["開", "所"], example: "연구소가 새로 개소했다." },
  { id: 51, word: "우모", hanja: "牛毛", reading: "우모", syllables: ["우", "모"], hanjaChars: ["牛", "毛"], example: "우모처럼 많은 수를 비유했다." },
  { id: 52, word: "번상", hanja: "番上", reading: "번상", syllables: ["번", "상"], hanjaChars: ["番", "上"], example: "군사가 번상에 나섰다." },
  { id: 53, word: "고등", hanja: "高等", reading: "고등", syllables: ["고", "등"], hanjaChars: ["高", "等"], example: "고등 교육을 받았다." },
  { id: 54, word: "광선", hanja: "光線", reading: "광선", syllables: ["광", "선"], hanjaChars: ["光", "線"], example: "햇빛의 광선이 비쳤다." },
  { id: 55, word: "천명", hanja: "天命", reading: "천명", syllables: ["천", "명"], hanjaChars: ["天", "命"], example: "그는 이를 천명으로 여겼다." },
  { id: 56, word: "합반", hanja: "合班", reading: "합반", syllables: ["합", "반"], hanjaChars: ["合", "班"], example: "학생 수가 적어 합반했다." },
  { id: 57, word: "강산", hanja: "江山", reading: "강산", syllables: ["강", "산"], hanjaChars: ["江", "山"], example: "강산이 수려하다." },
  { id: 58, word: "명야", hanja: "明夜", reading: "명야", syllables: ["명", "야"], hanjaChars: ["明", "夜"], example: "명야에 다시 만나자." },
  { id: 59, word: "영주", hanja: "永住", reading: "영주", syllables: ["영", "주"], hanjaChars: ["永", "住"], example: "이 도시에 영주할 계획이다." },
  { id: 60, word: "안전", hanja: "安全", reading: "안전", syllables: ["안", "전"], hanjaChars: ["安", "全"], example: "안전이 최우선이다." },
  { id: 61, word: "거래", hanja: "去來", reading: "거래", syllables: ["거", "래"], hanjaChars: ["去", "來"], example: "공정한 거래가 필요하다." },
  { id: 62, word: "민화", hanja: "民話", reading: "민화", syllables: ["민", "화"], hanjaChars: ["民", "話"], example: "민화에는 서민의 삶이 담겨 있다." },
  { id: 63, word: "상등", hanja: "上等", reading: "상등", syllables: ["상", "등"], hanjaChars: ["上", "等"], example: "상등 품질의 상품이다." },
  { id: 64, word: "서신", hanja: "書信", reading: "서신", syllables: ["서", "신"], hanjaChars: ["書", "信"], example: "오랜만에 서신을 주고받았다." },
  { id: 65, word: "심혈", hanja: "心血", reading: "심혈", syllables: ["심", "혈"], hanjaChars: ["心", "血"], example: "심혈을 기울여 준비했다." },
  { id: 66, word: "과목", hanja: "科目", reading: "과목", syllables: ["과", "목"], hanjaChars: ["科", "目"], example: "가장 좋아하는 과목이다." },
  { id: 67, word: "화력", hanja: "火力", reading: "화력", syllables: ["화", "력"], hanjaChars: ["火", "力"], example: "화력이 강한 발전소이다." },
  { id: 68, word: "인성", hanja: "人性", reading: "인성", syllables: ["인", "성"], hanjaChars: ["人", "性"], example: "인성이 바른 사람이 존중받는다." },
  { id: 69, word: "형부", hanja: "兄夫", reading: "형부", syllables: ["형", "부"], hanjaChars: ["兄", "夫"], example: "형부께서 방문하셨다." },
  { id: 70, word: "명문", hanja: "名門", reading: "명문", syllables: ["명", "문"], hanjaChars: ["名", "門"], example: "그는 명문가 출신이다." },
  { id: 71, word: "명가", hanja: "名家", reading: "명가", syllables: ["명", "가"], hanjaChars: ["名", "家"], example: "그 집안은 대대로 명가였다." },
  { id: 72, word: "원방", hanja: "遠方", reading: "원방", syllables: ["원", "방"], hanjaChars: ["遠", "方"], example: "원방에서 손님이 왔다." },
  { id: 73, word: "근방", hanja: "近方", reading: "근방", syllables: ["근", "방"], hanjaChars: ["近", "方"], example: "집 근방에 학교가 있다." },
  { id: 74, word: "만만부당", hanja: "萬萬不當", reading: "만만부당", syllables: ["만", "만", "부", "당"], hanjaChars: ["萬", "萬", "不", "當"], example: "그 요구는 만만부당하다." }
];


// 레벨 목록 정의
export const LEVELS = [
  { id: 8, label: '8급', data: HANJA_LEVEL_8, wordData: WORDS_TEXTBOOK_8, color: 'yellow', locked: false },
  { id: 7, label: '7급', data: HANJA_LEVEL_7, wordData: WORDS_TEXTBOOK_7, color: 'green', locked: false },
  { id: 6, label: '6급', data: HANJA_LEVEL_6, wordData: WORDS_TEXTBOOK_6, color: 'blue', locked: false },
  { id: 55, label: '준5급', data: HANJA_LEVEL_5_JUN, wordData: WORDS_TEXTBOOK_5_JUN, color: 'purple', locked: false },
  { id: 5, label: '5급', data: HANJA_LEVEL_5, wordData: WORDS_TEXTBOOK_5, color: 'red', locked: false },
];
